server {
    server_name manager-report.sappapp1b24.ru;

    location / {
        proxy_pass http://127.0.0.1:8099;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/manager-report.sappapp1b24.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/manager-report.sappapp1b24.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = manager-report.sappapp1b24.ru) {
        return 301 https://$host$request_uri;
    }
    server_name manager-report.sappapp1b24.ru;
    listen 80;
    return 404;
}