"""create initial tables

Revision ID: e9ab657a2a91
Revises: 
Create Date: 2026-05-27 12:46:24.031720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ab657a2a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bitrix_domain', sa.String(length=255), nullable=False),
    sa.Column('member_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bitrix_domain'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('portal_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', name='uq_portal_auth_portal_id')
    )
    op.create_table('portal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'key', name='uq_portal_settings_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('bitrix_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'bitrix_user_id', name='uq_users_portal_bitrix_user')
    )
    op.create_index('ix_users_portal_active', 'users', ['portal_id', 'is_active'], unique=False)
    op.create_table('manager_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manager_submissions_date_slot', 'manager_submissions', ['portal_id', 'report_date', 'slot'], unique=False)
    op.create_index('ix_manager_submissions_report', 'manager_submissions', ['portal_id', 'user_id', 'period_start', 'period_end'], unique=False)
    op.create_table('metric_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('plan_year', sa.Integer(), nullable=False),
    sa.Column('plan_month', sa.Integer(), nullable=False),
    sa.Column('daily_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monthly_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'user_id', 'metric_code', 'plan_year', 'plan_month', name='uq_metric_plan_month')
    )
    op.create_index('ix_metric_plans_metric', 'metric_plans', ['metric_code'], unique=False)
    op.create_index('ix_metric_plans_user_month', 'metric_plans', ['portal_id', 'user_id', 'plan_year', 'plan_month'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_logs_report', 'reminder_logs', ['portal_id', 'user_id', 'report_date', 'slot'], unique=False)
    op.create_index('ix_reminder_logs_status', 'reminder_logs', ['portal_id', 'status'], unique=False)
    op.create_table('system_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'user_id', 'period_start', 'period_end', name='uq_system_snapshot_period')
    )
    op.create_index('ix_system_snapshots_date', 'system_metric_snapshots', ['portal_id', 'report_date'], unique=False)
    op.create_index('ix_system_snapshots_report', 'system_metric_snapshots', ['portal_id', 'user_id', 'period_start', 'period_end'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_activity_logs_opened', 'user_activity_logs', ['portal_id', 'user_id', 'opened_at'], unique=False)
    op.create_table('manager_submission_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['manager_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'metric_code', name='uq_manager_submission_metric')
    )
    op.create_index('ix_manager_submission_values_metric', 'manager_submission_values', ['metric_code'], unique=False)
    op.create_table('system_metric_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['system_metric_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'metric_code', name='uq_system_snapshot_metric')
    )
    op.create_index('ix_system_metric_values_metric', 'system_metric_values', ['metric_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_metric_values_metric', table_name='system_metric_values')
    op.drop_table('system_metric_values')
    op.drop_index('ix_manager_submission_values_metric', table_name='manager_submission_values')
    op.drop_table('manager_submission_values')
    op.drop_index('ix_user_activity_logs_opened', table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index('ix_system_snapshots_report', table_name='system_metric_snapshots')
    op.drop_index('ix_system_snapshots_date', table_name='system_metric_snapshots')
    op.drop_table('system_metric_snapshots')
    op.drop_index('ix_reminder_logs_status', table_name='reminder_logs')
    op.drop_index('ix_reminder_logs_report', table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index('ix_metric_plans_user_month', table_name='metric_plans')
    op.drop_index('ix_metric_plans_metric', table_name='metric_plans')
    op.drop_table('metric_plans')
    op.drop_index('ix_manager_submissions_report', table_name='manager_submissions')
    op.drop_index('ix_manager_submissions_date_slot', table_name='manager_submissions')
    op.drop_table('manager_submissions')
    op.drop_index('ix_users_portal_active', table_name='users')
    op.drop_table('users')
    op.drop_table('portal_settings')
    op.drop_table('portal_auth')
    op.drop_table('portals')
    # ### end Alembic commands ###
